module.exports = {
  apps: [
    {
      name: "fitovance-server",
      cwd: "./server",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 4001,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      error_file: "/root/.pm2/logs/fitovance-server-error.log",
      out_file: "/root/.pm2/logs/fitovance-server-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
    {
      name: "fitovance-client",
      cwd: "./client",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3001",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "800M",
      error_file: "/root/.pm2/logs/fitovance-client-error.log",
      out_file: "/root/.pm2/logs/fitovance-client-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
    {
      name: "fitovance-front",
      cwd: "./front",
      script: "npm",
      args: "run preview -- --port 4174 --host 0.0.0.0",
      env: {
        NODE_ENV: "production",
        PORT: 4174,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      error_file: "/root/.pm2/logs/fitovance-front-error.log",
      out_file: "/root/.pm2/logs/fitovance-front-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
  ],
};
